# Generated by Django 4.1.5 on 2023-03-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='counts_likes',
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
